[Service]
Environment="COMPRESSION_RESTART_CMD=sudo systemctl restart gst-grid"
Environment="MEDIAMTX_CHECK_CMD=systemctl is-active mediamtx"
Environment="MEDIAMTX_RESTART_CMD=sudo systemctl restart mediamtx"
Environment="PTZ_RESTART_CMD=sudo systemctl restart vms-ptz"
